### ISSUE TITLE
first meetup prometheus slides are weird

### ISSUE THREAD

**Issue by marekaf** [CloudNativePrague/meetups#4]
@zloo https://github.com/CloudNativePrague/meetups/blob/master/2019/02_February/prometheus-histograms-grafana-heatmaps/prometheus-histograms-grafana-heatmaps.pdf this looks weird, images are missing, some captions as well

can you please take a look at it?:)

**Comment by zloo** [comment]
Thanks for noticing, I mistakenly created PDF from an old version of slides.

**Comment by marekaf** [comment]
great, thanks:)
